build: # images to build
  dev:
    client: 
      "lunyamwimages/boostedchatui-dev:latest": "LUNYAMWIDEVS/boostedchat.git      dev" # the repo url is use to get service name of repo given in heldRepos.md
    api: 
      "lunyamwimages/boostedchatapi-dev:latest": "LUNYAMWIDEVS/boostedchat-api.git      dev" 
    mqtt: 
      "lunyamwimages/boostedchatmqtt-dev:latest": "boostedchat/boostedchat-mqtt.git      dev"
    prompt: 
      "lunyamwimages/boostedchatmqtt-dev:latest": "boostedchat/boostedchat-mqtt.git      dev"
  airflow-dev:
    web: 
      "lunyamwimages/scrapper-dev:latest": "LUNYAMWIDEVS/boostedchat-scrapper.git      dev"
  main:
    client: 
      "lunyamwimages/boostedchatui:main": "LUNYAMWIDEVS/boostedchat.git      main" # the repo url is use to get service name of repo given in heldRepos.md
    api: 
      "lunyamwimages/boostedchatapi:main": "LUNYAMWIDEVS/boostedchat-api.git      main" 
    mqtt: 
      "lunyamwimages/boostedchatmqtt:main": "boostedchat/boostedchat-mqtt.git      main"
    prompt: 
      "lunyamwimages/boostedchatmqtt:main": "boostedchat/boostedchat-mqtt.git      main"
  airflow-main:
    web: 
      "lunyamwimages/scrapper:main": "LUNYAMWIDEVS/boostedchat-scrapper.git      main"



use: # images to use in the deployment. This section is not yet used. 
  dev:
    api: "lunyamwimages/boostedchatapi-dev:latest"    
    postgres: "postgres:latest"                       # not changed
    postgres-promptfactory: "postgres:latest"         # not changed
    client: "lunyamwimages/boostedchatui-dev:latest"
    certbot: "lunyamwimages/boostedchatmqtt"          # not changed
    prompt: "lunyamwimages/promptfactory"             # not changed
    salesrep: "lunyamwimages/boostedchatamqp"         # needs to be removed
    message-broker: "rabbitmq:3-management-alpine"    # needs to be removed

  airflow-dev:
    web: "lunyamwimages/scrapper-dev:latest"

  main: # not yet implemented

