name: Docker Build and Push

on:
  push:
    branches:
        - main

jobs:
  build:
    name: "Create Instance"
    if: startsWith(github.event.head_commit.message, 'build and deploy')
    runs-on: ubuntu-latest
    steps:
        -   uses: actions/checkout@v3
        -   name: Checkout repository
            uses: actions/checkout@v2

        -   name: Set Docker secrets based on branch
            if: github.ref == 'refs/heads/dev'
            run: |
                echo "::set-env name=DOCKER_USERNAME::${{ secrets.DEV_DOCKER_USERNAME }}"
                echo "::set-env name=DOCKER_PASSWORD::${{ secrets.DEV_DOCKER_PASSWORD }}"
        
        -   name: Set Docker secrets based on branch
            if: github.ref == 'refs/heads/main'
            run: |
                echo "::set-env name=DOCKER_USERNAME::${{ secrets.MAIN_DOCKER_USERNAME }}"
                echo "::set-env name=DOCKER_PASSWORD::${{ secrets.MAIN_DOCKER_PASSWORD }}"

        -   name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
                username: ${{ env.DOCKER_USERNAME }}
                password: ${{ env.DOCKER_PASSWORD }}

        # loop through all images that are to be built...

        -   name: Build and push Docker image
            run: |
                docker build -t your-dockerhub-username/your-image-name:latest .
                docker push your-dockerhub-username/your-image-name:latest