name: Trigger Dependent Repo Updates

on:
  workflow_dispatch:  # Manual trigger for testing
  push:
    paths:
      - deploymentWorkflowTemplate.yml

jobs:
  trigger_updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read file contents
        id: read_file
        run: |
          file_contents=$(cat deploymentWorkflowTemplate.yml | base64)
          file_contents=${file_contents//$'\n'/\\n}
          # echo $file_contents
          echo "::set-output name=file_contents::$file_contents"
      - name: Check output
        run: echo ${{ steps.read_file.outputs.file_contents }}
      - name: Trigger updates in dependent repos
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: LUNYAMWIDEVS/dispatchTesting  # Replace with actual repo names
          event-type: update-deployment-workflow 
        #   client-payload: # I want to send the contents of the file here  
          client-payload: '{ 
                "template_file_content":"${{ steps.read_file.outputs.file_contents }}"
            }'