name: Trigger Dependent Repo Updates

on:
  workflow_dispatch:  # Manual trigger for testing
  push:
    paths:
      - deploymentWorkflowTemplate.yml

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      file_contents: ${{ steps.read_file.outputs.file_contents }}
    steps:
      - uses: actions/checkout@v4
      - name: Read file contents
        id: read_file
        run: |
          file_contents=$(cat deploymentWorkflowTemplate.yml | base64 -w 0) # w  option specifies the maximum line length in characters for the output lines. Setting it to 0 effectively disables line wrapping
          echo "$file_contents"
          # echo "::set-output name=file_contents::$file_contents"
          echo "$file_contents" >> $GITHUB_OUTPUT
      - name: Get held repos list
        id: set-matrix
        run: |
          ./localscripts/getHeldRepos.sh 
          echo "matrix=$(jq -c . < ./heldRepos.json)" >> $GITHUB_OUTPUT
      # - name: Check output
      #   id: "file-contents"
      #   run: echo "${{ steps.read_file.outputs.file_contents }}"
  loop:
      runs-on: ubuntu-latest
      needs: 
        - setup
      strategy:
        matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
      steps:
        - uses: actions/checkout@v4
          with:
            repository: "${{ matrix.org }}/${{ matrix.repo }}"
            ref: "dev"
            token: ${{ secrets.REPO_ACCESS_TOKEN }}
        - run: echo "${{ matrix.org }}/${{ matrix.repo }}"
        # try writing directly to the repo
        - name: Replace service name
          id: replace-service-name
          run: |
            echo "${{ needs.setup.outputs.file_contents }}" | base64 -d > tmp_file_contents
            sed -i 's/SERVICE_NAME: "\$serviceName"/SERVICE_NAME: "${{ matrix.service }}"/g' tmp_file_contents
            # cat tmp_file_contents | base64 -w 0 > tmp_file_contents_encoded
            mv tmp_file_contents .github/workflows/pushToHoldingRepo.yaml
        # - name: Trigger updates in dependent repos
        #   uses: peter-evans/repository-dispatch@v3
        #   with:
        #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
        #     repository: "${{ matrix.org }}/${{ matrix.repo }}"
        #     event-type: update-deployment-workflow 
        #   #   client-payload: # I want to send the contents of the file here  
        #     client-payload: '{ 
        #           "template_file_content":"$(cat tmp_file_contents_encoded)"
        #       }'
        - uses: peaceiris/actions-gh-pages@v3
          with:
            # github_token: ${{ secrets.GITHUB_TOKEN }}
            personal_token: ${{ secrets.REPO_ACCESS_TOKEN }}
            publish_dir: ./  # Publish the root of your repo
            # publish_branch: "${{ matrix.service }}-${{ matrix.branch }}"
            external_repository: "${{ matrix.org }}/${{ matrix.repo }}"
            publish_branch: "dev"
            force_orphan: true # Overwrite the 'time' branch each time
            # commit_message: "Update pushToHoldingRepo from https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/commit/${{ github.sha }}"
            full_commit_message: ${{ github.event.head_commit.message }}
