name: Trigger Dependent Repo Updates

on:
  workflow_dispatch:  # Manual trigger for testing
  push:
    paths:
      - deploymentWorkflowTemplate.yml

jobs:
  trigger_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger updates in dependent repos
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: LUNYAMWIDEVS/dispatchTesting  # Replace with actual repo names
          event-type: update-deployment-workflow  
        #   repository: org-name/repo-name2
        #   event: update-deployment-workflow  
          # ... add more dependent repos as needed