name: Trigger Dependent Repo Updates

on:
  workflow_dispatch:  # Manual trigger for testing
  push:
    paths:
      - deploymentWorkflowTemplate.yml

jobs:
  trigger_updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read file contents
        id: read_file
        run: |
          file_contents=$(cat deploymentWorkflowTemplate.yml)
          echo "::set-output name=file_contents::$file_contents"
      - name: Trigger updates in dependent repos
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: LUNYAMWIDEVS/dispatchTesting  # Replace with actual repo names
          event-type: update-deployment-workflow 
        #   client-payload: # I want to send the contents of the file here  
          client-payload: ${{ steps.read_file.outputs.file_contents }}