name: React to Trigger from -Site

on:
  repository_dispatch:
    types: [updates_old]

jobs:
  deploy_to_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display environment
        run: echo "Deploying to ${{ github.event.client_payload.branch }}"