name: Triggered to Update Servers b-site
# log in to all servers
# git pull on all of them
# copy script to this other script

on:
  repository_dispatch:
    types: [update-site]
env:
  dev_vm_name: boostedchat-devs
jobs:
  get_instances:
    runs-on: ubuntu-latest
    # if: ${{github.event.client_payload.branch == 'dev' }}
    permissions:
          contents: 'read'
          id-token: 'write'
    outputs:
      vms: ${{ steps.list_instances.outputs.instances }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
      - name: List vms
        id: list_instances
        run: |
          gcloud compute instances list --format="value(name, zone)" > instances.txt
          cp instances.txt zones.txt
          sed -i 's/\s.*//' instances.txt # remove all but the first
          sed -i 's/.*\s\([^ ]*\)$/\1/' zones.txt # remove all but the last
          #   instances=$(cat instances.txt | base64 -w 0)
          # echo "instances=$instances" >> $GITHUB_OUTPUT
          instances=$(cat instances.txt)
          # it will be less resource intensive to run it from here
      - name: Loop and Update
        run: |
          cat instances.txt
          cat zones.txt
          echo "#!/bin/bash" > updateInstances.sh
          index=1
          while IFS= read -r instance; do
            echo $instance
            zone=$(sed -n "${index}p" zones.txt)
            ((index++))
            echo "gcloud compute scp setupscripts/update-site.sh $instance:/tmp/update-site.sh --zone=$zone" >> updateInstances.sh
            #echo "gcloud compute ssh $instance --zone=$zone --command=\"sudo chmod +x /tmp/update-site.sh \""  >> updateInstances.sh
            echo "gcloud compute ssh $instance --zone=$zone --command=\"sudo chmod +x /tmp/update-site.sh && sudo bash /tmp/update-site.sh\""  >> updateInstances.sh
          done < instances.txt
          cat updateInstances.sh
          bash updateInstances.sh
          sleep 30